# Generated by Django 5.2.15 on 2026-07-05 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('hostname', models.CharField(blank=True, max_length=180)),
                ('asset_type', models.CharField(max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('site', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_maintenance', 'In Maintenance'), ('archived', 'Archived')], default='active', max_length=32)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=32)),
                ('warranty_starts_on', models.DateField(blank=True, null=True)),
                ('warranty_expires_on', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to='accounts.adminuser')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assets', to='accounts.adminuser')),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['asset_tag'],
                'indexes': [models.Index(fields=['asset_tag'], name='assets_asset_tag_idx'), models.Index(fields=['status'], name='assets_status_idx'), models.Index(fields=['criticality'], name='assets_criticality_idx'), models.Index(fields=['asset_type'], name='assets_asset_type_idx'), models.Index(fields=['vendor'], name='assets_vendor_idx'), models.Index(fields=['site'], name='assets_site_idx'), models.Index(fields=['warranty_expires_on'], name='assets_warranty_exp_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('serial_number',), name='assets_serial_number_unique_when_present')],
            },
        ),
    ]
