# Generated by Django 5.2.15 on 2026-07-05 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='sites.site'),
        ),
    ]
