# Generated by Django 5.2.15 on 2026-07-05 13:33

import django.db.models.deletion
from django.db import migrations, models


def copy_primary_ip_addresses(apps, schema_editor):
    Asset = apps.get_model("assets", "Asset")
    AssetIPAddress = apps.get_model("assets", "AssetIPAddress")

    for asset in Asset.objects.exclude(ip_address__isnull=True).exclude(ip_address="").iterator():
        AssetIPAddress.objects.get_or_create(
            asset_id=asset.id,
            address=asset.ip_address,
            defaults={"is_primary": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assettype_devicetype_location_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='assets.asset')),
            ],
            options={
                'db_table': 'asset_ip_addresses',
                'ordering': ['-is_primary', 'address'],
                'indexes': [models.Index(fields=['asset'], name='asset_ip_addresses_asset_idx'), models.Index(fields=['address'], name='asset_ip_addresses_address_idx'), models.Index(fields=['is_primary'], name='asset_ip_addresses_primary_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'address'), name='asset_ip_addresses_asset_address_unique')],
            },
        ),
        migrations.RunPython(copy_primary_ip_addresses, migrations.RunPython.noop),
    ]
