# Generated by Django 5.2.15 on 2026-07-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_deleted_at_site_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
